### ISSUE TITLE
kubesphere v3.4.1如果在 webui 上部署文档中的 minecraft 测试镜像

### ISSUE THREAD

**Issue by symsimmy** [openkruise/kruise-game#130]
按照教程，我按照好了 kruise 和 kruise-game
<img width="500" alt="image" src="https://github.com/openkruise/kruise-game/assets/10104473/f7efc1ca-5bbc-46ac-882c-a578a443fb57">

但是，当我按照：https://openkruise.io/zh/kruisegame/installation，这个文档来部署游戏服服务时。
我使用下面的yaml：
```yaml
apiVersion: v1
kind: GameServerSet
metadata:
  name: minecraft
  namespace: kruise-game-system
  labels:
    app: minecraft
spec:
  replicas: 3
  updateStrategy:
    rollingUpdate:
      podUpdatePolicy: InPlaceIfPossible
  gameServerTemplate:
    spec:
      containers:
        - image: registry.cn-hangzhou.aliyuncs.com/acs/minecraft-demo:1.12.2
          name: minecraft
```
显示创建成功，但是没有创建：
<img width="500" alt="image" src="https://github.com/openkruise/kruise-game/assets/10104473/5aa4e9b0-be92-458c-a5b6-92e82c3338db">

我想请教下我的配置有什么问题么？

附：
1. kruise-webhook-service yaml：
```yaml
kind: Service
apiVersion: v1
metadata:
  name: kruise-webhook-service
  namespace: kruise-system
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubesphere.io/instance: kruise-cn7tvf
  annotations:
    meta.helm.sh/release-name: kruise-cn7tvf
    meta.helm.sh/release-namespace: okg-learn
spec:
  ports:
    - protocol: TCP
      port: 443
      targetPort: 9876
  selector:
    control-plane: controller-manager
  clusterIP: 10.233.28.39
  clusterIPs:
    - 10.233.28.39
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
```

2. kruise-game-controller-manager-metrics-service yaml：
```yaml
kind: Service
apiVersion: v1
metadata:
  name: kruise-game-controller-manager-metrics-service
  namespace: kruise-game-system
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubesphere.io/instance: kruise-game-b68lck
    control-plane: kruise-game-controller-manager
  annotations:
    meta.helm.sh/release-name: kruise-game-b68lck
    meta.helm.sh/release-namespace: okg-learn
spec:
  ports:
    - name: https
      protocol: TCP
      port: 8443
      targetPort: https
  selector:
    control-plane: kruise-game-controller-manager
  clusterIP: 10.233.48.173
  clusterIPs:
    - 10.233.48.173
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
```

3. kruise-game-external-scaler yaml：
```yaml
kind: Service
apiVersion: v1
metadata:
  name: kruise-game-external-scaler
  namespace: kruise-game-system
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubesphere.io/instance: kruise-game-b68lck
  annotations:
    meta.helm.sh/release-name: kruise-game-b68lck
    meta.helm.sh/release-namespace: okg-learn
spec:
  ports:
    - protocol: TCP
      port: 6000
      targetPort: 6000
  selector:
    control-plane: kruise-game-controller-manager
  clusterIP: 10.233.60.166
  clusterIPs:
    - 10.233.60.166
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster

```

4. kruise-game-webhook-service yaml：
```yaml
kind: Service
apiVersion: v1
metadata:
  name: kruise-game-webhook-service
  namespace: kruise-game-system
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubesphere.io/instance: kruise-game-b68lck
  annotations:
    meta.helm.sh/release-name: kruise-game-b68lck
    meta.helm.sh/release-namespace: okg-learn
spec:
  ports:
    - protocol: TCP
      port: 443
      targetPort: 9876
  selector:
    control-plane: kruise-game-controller-manager
  clusterIP: 10.233.22.252
  clusterIPs:
    - 10.233.22.252
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster

```
