### ISSUE TITLE
ReserveIds缩容结果非预期

### ISSUE THREAD

**Issue by shensl** [openkruise/kruise-game#152]
https://github.com/openkruise/kruise-game/blob/b6fdc2353e5da6a03d46c9ac6750aad862beaccf/docs/%E4%B8%AD%E6%96%87/%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B/%E6%B8%B8%E6%88%8F%E6%9C%8D%E6%B0%B4%E5%B9%B3%E4%BC%B8%E7%BC%A9.md?plain=1#L211
#### 初始状态
gss配置如下
```yaml
...
spec:
  replicas: 5
  reserveGameServerIds:
  - 0
  - 2
  scaleStrategy:
    scaleDownStrategyType: ReserveIds
...
```
gs信息如下
```shell
NAME          STATE   OPSSTATE   DP    UP    AGE
nginx-okg-1   Ready   None       0     0     23h
nginx-okg-3   Ready   None       0     0     6h57m
nginx-okg-4   Ready   None       0     0     7m26s
nginx-okg-5   Ready   None       0     0     7m26s
nginx-okg-6   Ready   None       0     0     6m19s
```
#### gss修改内容
```shell
kubectl edit gss nginx-okg
```
```yaml
spec:
  replicas: 3
  reserveGameServerIds:
  - 0
  - 4
  scaleStrategy:
    scaleDownStrategyType: ReserveIds
...
```
#### 修改提交后结果
```yaml
...
spec:
  replicas: 3
  reserveGameServerIds:
  - 0
  - 4
  - 6
  scaleStrategy:
    scaleDownStrategyType: ReserveIds
...
```
```shell
NAME          STATE   OPSSTATE   DP    UP    AGE
nginx-okg-1   Ready   None       0     0     24h
nginx-okg-2   Ready   None       0     0     2m9s
nginx-okg-3   Ready   None       0     0     7h3m
```

#### 预期结果
1、第一预期应该是gs保留[1, 3, 5]，reserveGameServerIds的值更新为[0, 4, 6]
2、目前还不理解新建gs-2的原理，假设新建gs-2符合预期的话，那么reserveGameServerIds的值为何不是更新为[0, 4, 5, 6]
