### ISSUE TITLE
Feat | Added a protection mechanism when scaling down

### ISSUE THREAD

**Issue by chrisliu1995** [openkruise/kruise-game#36]
## Background
The game server is stateful, and we need a protection mechanism to prevent the players who are playing the game from being affected when GameServerSet reducing the number of replicas.

## API Define

Introduce the scale down strategy in GameServerSet, and add a new type of scale down strategy called **protected**. When scale down type is **protected**, the user can select protected objects to prevent from being deleted.

There will be two types of protection policies here, one is the threshold type, GameServers whose priority is less than the threshold value will be protected, and the other is the specified type, which can select GameServers with specified ids or matching labels to be protected.

```
type ScaleStrategy struct {
	ScaleDown     ScaleDownStrategy `json:"scaleDown,omitempty"`
...
}

type ScaleDownStrategy struct {
	Type              ScaleDownStrategyType `json:"type,omitempty"`
	ProtectedStrategy ProtectedStrategy     `json:"protectedPolicy,omitempty"`
}

type ScaleDownStrategyType string

const (
	ProtectedScaleDownStrategyType ScaleDownStrategyType = "Protected"
)

type ProtectedStrategy struct {
	Type      ProtectedStrategyType      `json:"type,omitempty"`
	ThresholdStrategy ThresholdProtectedStrategy `json:"thresholdStrategy,omitempty"`
	SpecifiedStrategy SpecifiedProtectedStrategy `json:"specifiedStrategy,omitempty"`
}

type ProtectedStrategyType string

const (
	SpecifiedProtectedStrategyType ProtectedStrategyType = "Specified"
	ThresholdProtectedStrategyType ProtectedStrategyType = "Threshold"
)

type ThresholdProtectedStrategy struct {
	OpsState         OpsState            `json:"opsState,omitempty"`
	DeletionPriority *intstr.IntOrString `json:"deletionPriority,omitempty"`
}

type SpecifiedProtectedStrategy struct {
	GameServerIds  []int `json:"gameServerIds,omitempty"`
	LabelSelector metav1.LabelSelector `json:"labelSelector,omitempty"`
}
```

example 1：
```
apiVersion: game.kruise.io/v1alpha1
kind: GameServerSet
spec:
  scaleStrategy:
      scaleDown:
          type: protected
          protectedPolicy:
              type: threshold
              thresholdStrategy:
                  opsState: None
                  deletionPriority: 30
```

In this example, GameServers whose opsState is None and Maintaining, and GameServers whose deletionPriority is less than or equal to 30 will be protected.

example 2：
```
apiVersion: game.kruise.io/v1alpha1
kind: GameServerSet
spec:
  scaleStrategy:
      scaleDown:
          type: protected
          protectedPolicy:
              type: specified
              specifiedStrategy:
                  gameServerIds:
                    - 2
                    - 3
                  labelSelector:
                      matchLabels:
                          GameServerLabel: "xxx"
```
In this example, GameServers with serial numbers 2 and 3, and GameServers with GameServerLabel: "xxx" key-value pairs will be protected.

Also note that the replicas of the GameServerSet may be different from the actual number of GameServers when scaleDown Strategy type is protected.
