### ISSUE TITLE
Multiple ops state probe may conflict with each other

### ISSUE THREAD

**Issue by l10xbin** [openkruise/kruise-game#43]
e.g
```  
serviceQualities: # 设置了一个idle的服务质量
    - name: healthy
      containerName: minecraft
      permanent: false
      exec:
        command: ["bash", "./healthy.sh"]
      serviceQualityAction:
        - state: false
          opsState: Maintaining
        - state: true
          opsState: None
    - name: idle
      containerName: minecraft
      initialDelaySeconds: 10
      permanent: false
      exec:
        command: [ "bash", "./idle.sh" ]
      serviceQualityAction:
        - state: true
          opsState: WaitToBeDeleted
        - state: false
          opsState: None
```

Currently,
idle and healthy may conflict.

If the healthy probe return Maintaining and idle  next round idle return None but healthy still not healthy.

A better way could be make the ops state calls atomic, which means user only need one api and wrap those logic in the only api(sh or http etc)
